import OnCacheLineEvictedEventArgs from "../../Simulation/Events/OnCacheLineEvictedEventArgs";
import OnCacheLineLoadedEventArgs from "../../Simulation/Events/OnCacheLineLoadedEventArgs";
import OnMemoryAccessedEventArgs from "../../Simulation/Events/OnMemoryAccessedEventArgs";

/// Interface for classes that render parts of the simulation's visualization.
export default interface IRenderer
{
	/// Invoked when the simulation visualization begins.
	onSimulationStart(): void;

	/// Invoked when the simulation visualization completes.
	onSimulationFinished(): void;

	/// Invoked whenever a cache line is loaded into the cache.
	/// @param eventArgs Event arguments generated by the simulation.
	onCacheLineLoaded(eventArgs: OnCacheLineLoadedEventArgs): void;

	/// Invoked whenever a cache line is evicted from the cache.
	/// @param eventArgs Event arguments generated by the simulation.
	onCacheLineEvicted(eventArgs: OnCacheLineEvictedEventArgs): void;

	/// Invoked whenever a memory location is accessed.
	/// @param eventArgs Event arguments generated by the simulation.
	onMemoryAccessed(eventArgs: OnMemoryAccessedEventArgs): void;
}
